# Name of your site (displayed in the header)
name: Verde Ridge 2023

# Short bio or description (displayed in the header)
description: Covering fun neighborhood activities in Verde Ridge, including Neighborhood Olympics

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
url: "https://verderidge.fun"

# allow future posts to show up
future: true

permalink: /:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
